name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}