name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew
